### ISSUE TITLE
Version naming

### ISSUE THREAD

**Issue by martinlindhe** [rc0r/afl-utils#31]
Installing the package on osx, i notice this warning

    /usr/local/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('1.32-rcor') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

Not sure if it is anything to worry about though, so no patch provided :-)

```
$ ag 1.32-rcor
afl_utils.egg-info/dependency_links.txt
1:https://github.com/rc0r/exploitable/tarball/experimental#egg=exploitable-1.32-rcor

afl_utils.egg-info/requires.txt
1:exploitable==1.32-rcor

setup.py
23:    'exploitable==1.32-rcor',       # needed for gdb script execution
29:    'https://github.com/rc0r/exploitable/tarball/experimental#egg=exploitable-1.32-rcor'
```

**Comment by martinlindhe** [comment]
nm the noise. It was my fault for using python 2.7 (system default on osx)

**Comment by rc0r** [comment]
Well, the version naming of the hacked exploitable plugin does not comply with PEP 440 as indicated by the warning.
However I chose this naming in order to avoid conflicts with the original/official exploitable package. (f.e. to avoid pulling the wrong version from PyPI during afl-utils setup).
My hacked version is not intended for publication on PyPI, so I guess this should not be a problem.

afl-utils' `setup.py` automatically pulls the right exploitable package from my GH and installs it (use a virtualenv!). If you run into problems during setup, feel free to report issues or ask for guidance!

**Comment by martinlindhe** [comment]
Ah, I see! Yes i had a minor issue with setup, sending a patch.
