### ISSUE TITLE
Feature request: Implement -t option to afl-collect

### ISSUE THREAD

**Issue by fgeek** [rc0r/afl-utils#38]
Implement -t option to afl-collect to only collect samples, which does not exceed the timeout limit. This would make it easier to collect input files when decreasing original timeout in afl-multicore configuration file.

**Comment by rc0r** [comment]
Thanks for the suggestion!

Well, we only can apply a timeout during the verification phase (enabled using `-r`) because that's the only place we directly run the target process with the samples. Later during gdb script execution all we do is run gdb and supply the generated script. Then we don't have any means to kill a single target process that's causing a DoS condition and massively delays `afl-collect`'s script execution.
However since verification phase takes place **before** gdb script execution, problematic samples can be filtered out in advance. The only drawback is you **have to** use `-r [-rt <timeout>]` explicitly for this to work.

Alright, the change should be implemented in [verification_timeout](https://github.com/rc0r/afl-utils/tree/verification_timeout).

Could you test this a bit?
